### PR TITLE
setupHttpClient() now properly uses the configured private key

### PR DESCRIPTION
**Pull request by ghost**
Unless I messed things up, current version has an (obvious?) bug at line 29, Models\Client.php:

``` php
'query' => ['private_token' => 'TWr7iJtT3WkMQmZrNZzJ']
```

The private token is hardcoded. As a result, any method will fail with "401 Unauthorized" error.
I've made a simple change to fix this.

### CODE REVIEW

**Comment by adamgoose** [comment]
Bahaha well that's embarassing... Thanks for catching that!

**Comment by ghost** [comment]
Shouldn't there be a version bump right away so that users can `composer update` and actually use this library?

**Comment by adamgoose** [comment]
Sorry about that. It's been a busy week, playing catch-up after Laracon! It's all merged now. :)

**Comment by ghost** [comment]
Awesome, thanks ;)

**Pull request merged**
